workers_dev = true
name = "jmviel-siteweb"
compatibility_date = "2024-11-18"
main = "./build/server/index.js"
assets = { directory = "./build/client/" }
routes = [
  "*.jeanmichelviel.ca/*",
  "jeanmichelviel.ca/*"
]